### ISSUE TITLE
event bindings are not working properly

### ISSUE THREAD

**Issue by KiranMantha** [WebReflection/lighterhtml#75] opened 2019-11-17 06:50 UTC
event bindings are not working properly if there is class attribiute on node. Please find the screenshot of issue

![image](https://user-images.githubusercontent.com/13364465/69004143-683d0400-0934-11ea-9bcb-cfaad415d2eb.png)

In above image, my change event on dropdown is transformed to class attribute. I tried in multiple ways for binding but all is in vain. the issue can also be reproducable if the parent node has class attribute. Please help me on this.

**Comment by yuretz** [comment] 2019-11-17 09:23
Well, I'm pretty sure, a screenshot is not enough for us to be able to help you. Could you maybe create a minimal reproduction example on CodePen / JsFiddle / something like this, so that we can see what's going on?

**Comment by WebReflection** [comment] 2019-11-17 09:52
It makes no sense to show me the layout, I need to see what are you doing to create such layout.

I am closing this until there is something to investigate.

**Closed by WebReflection** 2019-11-17 09:52 UTC

**Comment by KiranMantha** [comment] 2019-11-22 04:25
Sorry for late reply. 
I'm writing a framework based on lighterhtml named plumejs. It is built using typescript. The below is a ui library built on top of plumejs.
please find my repo [here](https://github.com/kiranmantha/plume-ui). 
please clone to your local and checkout to dev-branch.

`npm start` to run the application and you can find the above issue reproducable.

**Comment by KiranMantha** [comment] 2019-11-24 10:23
when i downgraded domtagger version to 0.4.0 from 0.5.11 the issue is resolved. Don't know why the downgrade worked

**Comment by WebReflection** [comment] 2019-11-24 10:33
Can you please provide a minimal example of a failing case? Cloning a whole project and investigate by myself is **not** how filing a bug works.

If you want me to understand any issue and fix it, I need you to help me out as much as you can.

Thank you.

**Comment by WebReflection** [comment] 2019-11-24 18:35
Just FYI, I've written a guide on how to file issues https://medium.com/@WebReflection/how-to-file-a-github-lab-issue-7080b8c0cef5 and I hope it'll help you next time you have an issue here, or elsewhere.

**Comment by KiranMantha** [comment] 2019-11-26 05:01
thankyou for providing conduct link. The problem is on my side as i'm using lighterhtml-plus but not lighterhtml which is causing compatability issue with latest domtagger version. When i used latest lighterhtml version, i didn't faced this issue . Sorry for troubling you for not providing a plunker or stackblitz link for reproduction and thanks for you paitience. :)

**Comment by WebReflection** [comment] 2019-11-26 07:58
So, to clarify:
  * if you use lighterhtml with latest domtagger everything works
  * if you use lighterhtml-plus with, or without, latest domtagger, it fails

Is that correct? I admittedly moved forward lighterhtml without updating its counter part lighterhtml-plus, but I start thinking I should probably divide these two as separate repositories so that bugs can be filed independently, since these are indeed pretty different libraries.

**Comment by KiranMantha** [comment] 2019-11-27 02:07
Exactly, there is no issue if i use lighterhtml with latest domtagger but if i use lighterhtml-plus with latest domtagger, i faced multiple issue like cloneNode of null or transforming events as classes. Seperating both of them is pretty good idea.

**Comment by WebReflection** [comment] 2019-11-27 06:45
I've created a repository a part for [lighterhtml-plus](https://github.com/WebReflection/lighterhtml-plus#readme) and it's literally copy and pasting _lighterhtml_ just adding [a patch](https://github.com/WebReflection/lighterhtml-plus/blob/master/plus.js) on top.

The version has been updated, and my effort at maintaining the `-plus` version too minimized to the extreme (it's an `npm run build` away, nothing else).

I hope you won't have issues with that, as it uses already everything _lighterhtml_ uses too 👋
