### ISSUE TITLE
Mozilla Firefox issue

### ISSUE THREAD

**Issue by alexey13** [WebReflection/lighterhtml#46] opened 2019-06-12 10:32 UTC
Good day, Andrea! Catch some strange bug. After some time node lost its communication with the object.
**1. How to replicate**
Open https://codepen.io/WebReflection/pen/LvqPOR in Mozilla Firefox. After some time (10 -20 minutes) get back to the window and click on button "BUTTON".
**2. What happens?**
Counter not change its value. Its stay 0.

Video of bug (https://www.dropbox.com/s/ypujayapq5vo9dh/2019-06-12-13-24-51%20%28online-video-cutter.com%29.mp4?dl=0)

**Comment by alexey13** [comment] 2019-06-12 10:42
Looks like its related to html.for()

**Comment by WebReflection** [comment] 2019-06-12 10:47
let's drop codepen out of the equation, since it's not the first time stuff breaks there but works on regular sites, thanks.

once you can confirm the bug exists also in localhost/sites, I'll have a look.

**Comment by alexey13** [comment] 2019-06-12 11:53
Yep, same on site. First i got it on site, after started to search your example to confirm. I should made same but not on codepen?

**Comment by WebReflection** [comment] 2019-06-12 12:51
so, my Firefox works here:
https://codepen.io/WebReflection/pen/LvqPOR

but it looks like you misunderstood few parts.

To start with, if you use `handleEvent` you **never** need to bind anything, if you pass `this` as event listener.

all calls like `this.render = this.render.bind(this)` are useless.

moreover, you never pass the render right away, you want to eventually pass the rendered result.

`this.btn.render` is not what you want, while `this.btn.render()` is ... you are working with nodes, pass nodes around, not callbacks, and `render()` should return a node in your case.

Same goes for `render(document.body, app.render)` ... it's wrong, you want to pass a callback that returns the node, so `render(document.body, () => app.render())` is better.

That being said, not sure I've solved your issue, specially 'cause I cannot reproduce it.

Do you have problems in Chrome or Safari? Which version of Firefox?

**Comment by alexey13** [comment] 2019-06-12 13:00
Thanks for the answer but I just took first of your live examples with html.for() and tested it to see will bug appear. Mozilla 67.0.1 (64). I not tested with Chrome but will. Just need to open page and wait for some time, try to wait longer. How can i debug it?

**Comment by WebReflection** [comment] 2019-06-12 13:05
> I just took first of your live examples with html.for()

can you please point me at such example? 'cause if it does `this.render = this.render.bind(this)` is plain wrong.

> Mozilla 67.0.1 (64)

I'm on  Mozilla 67.0.2 (64) here, still can't reproduce.

> open page and wait for some time

how long? I've waited 15 minutes before answering with my previous comment

**Comment by alexey13** [comment] 2019-06-12 13:15
> how long? I've waited 15 minutes before answering with my previous comment
Thats the thing its totally random. But in most cases its 10-20 minutes. Sometimes its working for hours. I cant understand what activity cause that bug and how to debug it.

> can you please point me at such example? 'cause if it does this.render = this.render.bind(this) is plain wrong.
This one. Its yours. https://codepen.io/WebReflection/pen/LvqPOR
As i can see you not used this.render = this.render.bind(this) in that example.

**Comment by alexey13** [comment] 2019-06-12 13:16
And yes, i checked Chrome time after time and it working perfect

**Comment by WebReflection** [comment] 2019-06-12 13:18
14 minutes ... still working
![Screenshot from 2019-06-12 15-17-44](https://user-images.githubusercontent.com/85749/59354371-499f6500-8d25-11e9-9bff-78b0aade42ff.png)

**Comment by alexey13** [comment] 2019-06-12 13:19
What should i do? If i will make a nonstop video will it be the reason to think that i not crazy?:)))

**Comment by WebReflection** [comment] 2019-06-12 13:20
> I cant understand what activity cause that bug and how to debug it.

I can, it's the same ugly WeakMap/Set bug that affected Webkit too. If they get rid of instances that are still used, everything breaks.

This is not an hyper/lighterHTML issue only though, it's a disaster in terms of reliability.

**Comment by alexey13** [comment] 2019-06-12 13:20
Hmmm...
Maybe its related to my browser addons. Its idea

**Comment by WebReflection** [comment] 2019-06-12 13:26
if your addons interfere with the DOM anyhow, than yes, but that's also nothing I can do in such case, just drop the `html.for(this)` and simply return `html` in the render.

It wont' be keyed, but at least you should never have such issue.

**Comment by alexey13** [comment] 2019-06-12 13:31
> I can, it's the same ugly WeakMap/Set bug that affected Webkit too. If they get rid of instances that are still used, everything breaks.

Ohh, its nasty.

> just drop the html.for(this) and simply return html in the render.

I love html.for(). When i use html - onconnected fires every rerender, what is not perfect for me

**Comment by WebReflection** [comment] 2019-06-12 13:49
btw, I still cannot reproduce. Please try to figure out which addon is interfering, hoping that's the issue, and not the WeakMap randomly losing references.

**Comment by alexey13** [comment] 2019-06-12 13:51
Ok, will test and let you know. Thanks Andrea!

**Comment by WebReflection** [comment] 2019-06-12 13:54
P.S. not only 'cause I work there, mostly 'cause we ship hyperHTML in production within the extension (and to roughly 100M users) I can confirm I have no issue whatsoever with [ABP](https://adblockplus.org/)

I know this is lighterhtml, but the underlying template literal parser/engine is exactly the same.

Please do let me know if you find the addon causing troubles, so we can either file them a bug, or write in this README that some browser plugin can make 3rd parts software unreliable.

Thanks.

**Comment by alexey13** [comment] 2019-06-12 14:01
Ok, i almost sure that addon must be a reason. Because bug appear in 2 mozilla browsers that i use (same addons installed) on different pcs

**Comment by WebReflection** [comment] 2019-06-12 14:09
you can go in `about:addons` and disable (without removing) all of them, then start fresh the browser and see if it's still doing that.

if it does, it'd be cool to know the exact add-on name that is causing the issue.

**Comment by WebReflection** [comment] 2019-06-12 15:03
to clarify, the codepen console is useless when there are errors. you need to bring up the real console and see if there's anything in there.

**Comment by alexey13** [comment] 2019-06-12 15:06
no errors in console  https://www.dropbox.com/s/6dwhpw8i2wbzcmw/2019-06-12-18-04-17.mp4?dl=0

**Comment by alexey13** [comment] 2019-06-12 15:11
Chrome working, no problems. All that time window where open. In firefox got bug several times. Chrome - zero

**Comment by WebReflection** [comment] 2019-06-12 15:30
I never had a single issue with Firefox evefr, so I'm closing this until I am able to reproduce.

**Comment by alexey13** [comment] 2019-06-13 06:59
Good day! I tested on 3 different PCs (windows) and mobile phone (android firefox). Bug in place on all of them. Can we request the help of the community to test with us?
Here is what I do: 
1. open https://codepen.io/WebReflection/pen/LvqPOR
2. Leave that page alone for an hour (bug appear faster, but to be sure). Just do other stuff that you do on the device 
3. Get back to a page and click on "BUTTON" (not "TEST"). If counter not changed you have got a bug too.

If counter changed repeat steps, please.

**Comment by WebReflection** [comment] 2019-06-13 07:56
opened tab now ... I'll leave it there for a hour

**Comment by WebReflection** [comment] 2019-06-13 08:15
OK, I've got it. Will try to figure out what the hell is happening in Firefox. This is **super** annoying, 'cause it comes from internals.

**Comment by WebReflection** [comment] 2019-06-13 08:30
Can you please check the console output of this test:
https://jsbin.com/peniburaho/1/edit?html,console,output

or put this tab in hold for a while:
https://codepen.io/WebReflection/pen/OdVrqN?editors=0010

and tell me if you ever see the log `New ref 😢` or as alert saying `different template` ?

**Comment by alexey13** [comment] 2019-06-13 08:32
Ok, opened, will let you know

**Comment by WebReflection** [comment] 2019-06-13 08:36
oh gosh ... this is bad https://bugzilla.mozilla.org/show_bug.cgi?id=1514421

**Comment by alexey13** [comment] 2019-06-13 08:40
Oh, i was thinking that it's related to memory (lost connection to node). Looks like it is so.

**Comment by WebReflection** [comment] 2019-06-13 09:22
busted!

![Screenshot from 2019-06-13 11-22-07](https://user-images.githubusercontent.com/85749/59420671-95a5e480-8dcd-11e9-9b5c-a5acb41a86c5.png)

**Comment by alexey13** [comment] 2019-06-13 09:29
Myne still holding:) 26200

**Comment by WebReflection** [comment] 2019-06-13 09:39
it looks like with the console open I cannot ever encounter this issue though ... including the code pen.

**Comment by alexey13** [comment] 2019-06-13 09:50
i am not sure on 100% but even with the console open soon or a later it will die

**Comment by WebReflection** [comment] 2019-06-13 09:58
mine still working, and it's been a while. the other test though ... 
![Screenshot from 2019-06-13 11-55-07](https://user-images.githubusercontent.com/85749/59423467-7c536700-8dd2-11e9-9cdb-4337d0ee65a5.png)

**Comment by WebReflection** [comment] 2019-06-13 10:30
Do you mind checking if with `lighterhtml@0.14.3` we have Firefox working as expected?

**Comment by alexey13** [comment] 2019-06-13 10:32
Wow, big thanks! Will check

**Comment by alexey13** [comment] 2019-06-13 10:34
I am using lighterhtml-plus. Will you update it too, please?

**Comment by WebReflection** [comment] 2019-06-13 10:36
please verify everything is fine with the usual code pen. I have updated it to use latest lighterhtml.

once we are sure everything is fine, I'll update the `plus` version too. 

before is kinda unnecessary 😅

**Comment by alexey13** [comment] 2019-06-13 10:38
hahahaha, you right I am too hurry. Will test

**Comment by thipages** [comment] 2019-06-13 10:44
Hi,
with Firefox 67.0.1 I got a match at 8600

for the test code, it might be useful to track and show new ref occurences

![image](https://user-images.githubusercontent.com/130309/59426607-e1aa5680-8dd8-11e9-9176-c5749d89a687.png)

**Comment by thipages** [comment] 2019-06-13 11:17
for info with Firefox 67.0.2 I got "[12200,14800] - wait 20100"

**Comment by WebReflection** [comment] 2019-06-13 11:20
@thipages we all get that, and it's already enough to demonstrate there is an issue in Firefox when it comes to collect template literals ... now, what I am after, is the initial test case:
https://github.com/WebReflection/lighterhtml/issues/46#issue-455135821

I have put Firefox beside Safari and badly transpiled TypeScript, penalizing performance per each template literal due unreliability of its greedy GC operations.

This is very sad, but I want to be sure the issue is also solved.

**Comment by alexey13** [comment] 2019-06-13 11:34
Checked several times this one https://codepen.io/WebReflection/pen/LvqPOR
All working fine.

**Comment by WebReflection** [comment] 2019-06-13 11:44
@alexey13 I've found a better approach that uses WeakMap to store a slow-path *once* template literal, meaning performance won't be penalized too much, and some slow down will happen only when the GC hits, but then again, every other call will be just fine.

This needs a whole refactoring of one of the core libs, but it should be there soon.

**Comment by alexey13** [comment] 2019-06-13 11:47
It's just perfect! Will wait of course

**Comment by WebReflection** [comment] 2019-06-13 12:41
OK, last update: both `lighterhtml` and `-plus` has been updated to use latest core that takes care of making template literals unique.

I'd like for everyone to confirm this page still works as expected (I've already updated the lib version)
https://codepen.io/WebReflection/pen/LvqPOR

So I can close this and update also hyperHTML.

Thank You!

**Comment by alexey13** [comment] 2019-06-13 12:43
Awesome! Opened, testing!

**Comment by alexey13** [comment] 2019-06-13 13:39
Had no bugs. Tested several times.

**Closed** 2019-06-13 13:44 UTC
Labels: bug
